export interface Tag {
    name: string;
}

export const tags: Tag[] = [
    { name: "acc.xyz.x" },
    { name: "acc.xyz.y" },
    { name: "acc.xyz.z" },
    /* the following tags from the database do not make sense (or there is not much data for them,
       so these tags are not offered to the end user
    { name: "batch" },
    { name: "disk.percent" },
    { name: "ec2x.data_usage" },
    { name: "event.system.device.ec2x" },
    { name: "event.system.device.ec2x.gnss" },
    { name: "event.system.disk.boot" },
    { name: "event.system.kernel" },
    { name: "event.system.minion" },
    { name: "event.system.network.wwan0" },
    { name: "event.system.power" },
    { name: "event.system.release" },
    { name: "event.system.sleep_timer.event_driven" },
    { name: "event.system.sleep_timer.inactivity_after_sleep" },
    { name: "event.system.sleep_timer.inactivity_fallback" },
    { name: "event.system.stn" },
    { name: "event.system.time" },
    { name: "event.vehicle.battery" },
    { name: "event.vehicle.engine" },
    { name: "event.vehicle.motor" },
    { name: "event.vehicle.position" },
    { name: "friction" },
    { name: "event.vehicle.position" },
    { name: "my_monitoring.disk_threshold_trigger" },
    { name: "noise"},
     */
    { name: "obd.acc_long" },
    { name: "obd.acc_trans" },
    { name: "obd.acc_yaw" },
    { name: "obd.asr_trq_req_dyn" },
    { name: "obd.asr_trq_req_st" },
    { name: "obd.bat" },
    { name: "obd.brk_trq_elec" },
    { name: "obd.brk_trq_req_dvr" },
    { name: "obd.brk_trq_req_elec" },
    { name: "obd.cons_avg" },
    { name: "obd.f_dist" },
    { name: "obd.msr_trq_req" },
    { name: "obd.odo" },
    { name: "obd.rpm" },
    { name: "obd.rpm_elec" },
    { name: "obd.rpm_fl" },
    { name: "obd.rpm_fr" },
    { name: "obd.rpm_rl" },
    { name: "obd.rpm_rr" },
    { name: "obd.sb_rem_fl" },
    { name: "obd.sb_rem_fr" },
    { name: "obd.sb_stat_rc" },
    { name: "obd.sb_stat_rl" },
    { name: "obd.sb_stat_rr" },
    { name: "obd.spd" },
    { name: "obd.spd_veh" },
    { name: "obd.strg_acc" },
    { name: "obd.strg_ang" },
    { name: "obd.strg_pos" },
    { name: "obd.temp" },
    { name: "obd.temp_ext" },
    { name: "obd.time" },
    { name: "obd.trac_cons" },
    { name: "obd.trip_cons" },
    { name: "obd.trip_cons_avg" },
    { name: "obd.trip_dist" },
    { name: "obd.trip_spd_avg" },
    { name: "obd.trq_eff" },
    { name: "obd.trq_req" },
    { name: "obd.whl_prs_fl" },
    { name: "obd.whl_prs_fr" },
    { name: "obd.whl_prs_rl" },
    { name: "obd.whl_prs_rr" },
    { name: "obd.whl_trq_est" },
    { name: "obd.whl_trq_pot_ri" },
    { name: "obd.ww_f_req" },
    { name: "obd.ww_f_stat" },
    { name: "obd.ww_f_stop" },
    { name: "rpi.temp" },
    { name: "track.pos" }

]

